#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engage.Survey.Entities
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="campus_dnn2")]
	public partial class SurveyModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertQuestion(Question instance);
    partial void UpdateQuestion(Question instance);
    partial void DeleteQuestion(Question instance);
    partial void InsertSection(Section instance);
    partial void UpdateSection(Section instance);
    partial void DeleteSection(Section instance);
    partial void InsertAnswer(Answer instance);
    partial void UpdateAnswer(Answer instance);
    partial void DeleteAnswer(Answer instance);
    partial void InsertResponseHeader(ResponseHeader instance);
    partial void UpdateResponseHeader(ResponseHeader instance);
    partial void DeleteResponseHeader(ResponseHeader instance);
    partial void InsertSurvey(Survey instance);
    partial void UpdateSurvey(Survey instance);
    partial void DeleteSurvey(Survey instance);
    partial void InsertResponse(Response instance);
    partial void UpdateResponse(Response instance);
    partial void DeleteResponse(Response instance);
    #endregion
		
		public SurveyModelDataContext() : 
				base(global::Engage.Survey.Entities.Properties.Settings.Default.campus_dnn2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SurveyModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SurveyModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SurveyModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SurveyModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Question> Questions
		{
			get
			{
				return this.GetTable<Question>();
			}
		}
		
		public System.Data.Linq.Table<Section> Sections
		{
			get
			{
				return this.GetTable<Section>();
			}
		}
		
		public System.Data.Linq.Table<Answer> Answers
		{
			get
			{
				return this.GetTable<Answer>();
			}
		}
		
		public System.Data.Linq.Table<ResponseHeader> ResponseHeaders
		{
			get
			{
				return this.GetTable<ResponseHeader>();
			}
		}
		
		public System.Data.Linq.Table<Survey> Surveys
		{
			get
			{
				return this.GetTable<Survey>();
			}
		}
		
		public System.Data.Linq.Table<Response> Responses
		{
			get
			{
				return this.GetTable<Response>();
			}
		}
	}
	
	[Table(Name="dbo.EngageSurvey_Question")]
	public partial class Question : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _QuestionId;
		
		private int _SectionId;
		
		private string _Text;
		
		private bool _ShowText;
		
		private bool _IsRequired;
		
		private string _RequiredMessage;
		
		private int _RelativeOrder;
		
		private int _SelectionLimit;
		
		private string _ControlType;
		
		private int _RevisingUser;
		
		private System.DateTime _RevisionDate;
		
		private int _CreatedBy;
		
		private System.DateTime _CreationDate;
		
		private EntitySet<Answer> _Answers;
		
		private EntityRef<Section> _Section;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQuestionIdChanging(int value);
    partial void OnQuestionIdChanged();
    partial void OnSectionIdChanging(int value);
    partial void OnSectionIdChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    partial void OnShowTextChanging(bool value);
    partial void OnShowTextChanged();
    partial void OnIsRequiredChanging(bool value);
    partial void OnIsRequiredChanged();
    partial void OnRequiredMessageChanging(string value);
    partial void OnRequiredMessageChanged();
    partial void OnRelativeOrderChanging(int value);
    partial void OnRelativeOrderChanged();
    partial void OnSelectionLimitChanging(int value);
    partial void OnSelectionLimitChanged();
    partial void OnControlTypeChanging(string value);
    partial void OnControlTypeChanged();
    partial void OnRevisingUserChanging(int value);
    partial void OnRevisingUserChanged();
    partial void OnRevisionDateChanging(System.DateTime value);
    partial void OnRevisionDateChanged();
    partial void OnCreatedByChanging(int value);
    partial void OnCreatedByChanged();
    partial void OnCreationDateChanging(System.DateTime value);
    partial void OnCreationDateChanged();
    #endregion
		
		public Question()
		{
			this._Answers = new EntitySet<Answer>(new Action<Answer>(this.attach_Answers), new Action<Answer>(this.detach_Answers));
			this._Section = default(EntityRef<Section>);
			OnCreated();
		}
		
		[Column(Storage="_QuestionId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int QuestionId
		{
			get
			{
				return this._QuestionId;
			}
			set
			{
				if ((this._QuestionId != value))
				{
					this.OnQuestionIdChanging(value);
					this.SendPropertyChanging();
					this._QuestionId = value;
					this.SendPropertyChanged("QuestionId");
					this.OnQuestionIdChanged();
				}
			}
		}
		
		[Column(Storage="_SectionId", DbType="Int NOT NULL")]
		public int SectionId
		{
			get
			{
				return this._SectionId;
			}
			set
			{
				if ((this._SectionId != value))
				{
					if (this._Section.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSectionIdChanging(value);
					this.SendPropertyChanging();
					this._SectionId = value;
					this.SendPropertyChanged("SectionId");
					this.OnSectionIdChanged();
				}
			}
		}
		
		[Column(Storage="_Text", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[Column(Storage="_ShowText", DbType="Bit NOT NULL")]
		public bool ShowText
		{
			get
			{
				return this._ShowText;
			}
			set
			{
				if ((this._ShowText != value))
				{
					this.OnShowTextChanging(value);
					this.SendPropertyChanging();
					this._ShowText = value;
					this.SendPropertyChanged("ShowText");
					this.OnShowTextChanged();
				}
			}
		}
		
		[Column(Storage="_IsRequired", DbType="Bit NOT NULL")]
		public bool IsRequired
		{
			get
			{
				return this._IsRequired;
			}
			set
			{
				if ((this._IsRequired != value))
				{
					this.OnIsRequiredChanging(value);
					this.SendPropertyChanging();
					this._IsRequired = value;
					this.SendPropertyChanged("IsRequired");
					this.OnIsRequiredChanged();
				}
			}
		}
		
		[Column(Storage="_RequiredMessage", DbType="NChar(256)")]
		public string RequiredMessage
		{
			get
			{
				return this._RequiredMessage;
			}
			set
			{
				if ((this._RequiredMessage != value))
				{
					this.OnRequiredMessageChanging(value);
					this.SendPropertyChanging();
					this._RequiredMessage = value;
					this.SendPropertyChanged("RequiredMessage");
					this.OnRequiredMessageChanged();
				}
			}
		}
		
		[Column(Storage="_RelativeOrder", DbType="Int NOT NULL")]
		public int RelativeOrder
		{
			get
			{
				return this._RelativeOrder;
			}
			set
			{
				if ((this._RelativeOrder != value))
				{
					this.OnRelativeOrderChanging(value);
					this.SendPropertyChanging();
					this._RelativeOrder = value;
					this.SendPropertyChanged("RelativeOrder");
					this.OnRelativeOrderChanged();
				}
			}
		}
		
		[Column(Storage="_SelectionLimit", DbType="Int NOT NULL")]
		public int SelectionLimit
		{
			get
			{
				return this._SelectionLimit;
			}
			set
			{
				if ((this._SelectionLimit != value))
				{
					this.OnSelectionLimitChanging(value);
					this.SendPropertyChanging();
					this._SelectionLimit = value;
					this.SendPropertyChanged("SelectionLimit");
					this.OnSelectionLimitChanged();
				}
			}
		}
		
		[Column(Storage="_ControlType", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string ControlType
		{
			get
			{
				return this._ControlType;
			}
			set
			{
				if ((this._ControlType != value))
				{
					this.OnControlTypeChanging(value);
					this.SendPropertyChanging();
					this._ControlType = value;
					this.SendPropertyChanged("ControlType");
					this.OnControlTypeChanged();
				}
			}
		}
		
		[Column(Storage="_RevisingUser", DbType="Int NOT NULL")]
		public int RevisingUser
		{
			get
			{
				return this._RevisingUser;
			}
			set
			{
				if ((this._RevisingUser != value))
				{
					this.OnRevisingUserChanging(value);
					this.SendPropertyChanging();
					this._RevisingUser = value;
					this.SendPropertyChanged("RevisingUser");
					this.OnRevisingUserChanged();
				}
			}
		}
		
		[Column(Storage="_RevisionDate", DbType="DateTime NOT NULL")]
		public System.DateTime RevisionDate
		{
			get
			{
				return this._RevisionDate;
			}
			set
			{
				if ((this._RevisionDate != value))
				{
					this.OnRevisionDateChanging(value);
					this.SendPropertyChanging();
					this._RevisionDate = value;
					this.SendPropertyChanged("RevisionDate");
					this.OnRevisionDateChanged();
				}
			}
		}
		
		[Column(Storage="_CreatedBy", DbType="Int NOT NULL")]
		public int CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[Column(Storage="_CreationDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreationDate
		{
			get
			{
				return this._CreationDate;
			}
			set
			{
				if ((this._CreationDate != value))
				{
					this.OnCreationDateChanging(value);
					this.SendPropertyChanging();
					this._CreationDate = value;
					this.SendPropertyChanged("CreationDate");
					this.OnCreationDateChanged();
				}
			}
		}
		
		[Association(Name="Question_Answer", Storage="_Answers", ThisKey="QuestionId", OtherKey="QuestionId")]
		public EntitySet<Answer> Answers
		{
			get
			{
				return this._Answers;
			}
			set
			{
				this._Answers.Assign(value);
			}
		}
		
		[Association(Name="Section_Question", Storage="_Section", ThisKey="SectionId", OtherKey="SectionId", IsForeignKey=true)]
		public Section Section
		{
			get
			{
				return this._Section.Entity;
			}
			set
			{
				Section previousValue = this._Section.Entity;
				if (((previousValue != value) 
							|| (this._Section.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Section.Entity = null;
						previousValue.Questions.Remove(this);
					}
					this._Section.Entity = value;
					if ((value != null))
					{
						value.Questions.Add(this);
						this._SectionId = value.SectionId;
					}
					else
					{
						this._SectionId = default(int);
					}
					this.SendPropertyChanged("Section");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Answers(Answer entity)
		{
			this.SendPropertyChanging();
			entity.Question = this;
		}
		
		private void detach_Answers(Answer entity)
		{
			this.SendPropertyChanging();
			entity.Question = null;
		}
	}
	
	[Table(Name="dbo.EngageSurvey_Section")]
	public partial class Section : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SectionId;
		
		private int _SurveyId;
		
		private string _Text;
		
		private bool _ShowText;
		
		private int _RelativeOrder;
		
		private int _RevisingUser;
		
		private System.DateTime _RevisionDate;
		
		private int _CreatedBy;
		
		private System.DateTime _CreationDate;
		
		private EntitySet<Question> _Questions;
		
		private EntityRef<Survey> _Survey;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSectionIdChanging(int value);
    partial void OnSectionIdChanged();
    partial void OnSurveyIdChanging(int value);
    partial void OnSurveyIdChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    partial void OnShowTextChanging(bool value);
    partial void OnShowTextChanged();
    partial void OnRelativeOrderChanging(int value);
    partial void OnRelativeOrderChanged();
    partial void OnRevisingUserChanging(int value);
    partial void OnRevisingUserChanged();
    partial void OnRevisionDateChanging(System.DateTime value);
    partial void OnRevisionDateChanged();
    partial void OnCreatedByChanging(int value);
    partial void OnCreatedByChanged();
    partial void OnCreationDateChanging(System.DateTime value);
    partial void OnCreationDateChanged();
    #endregion
		
		public Section()
		{
			this._Questions = new EntitySet<Question>(new Action<Question>(this.attach_Questions), new Action<Question>(this.detach_Questions));
			this._Survey = default(EntityRef<Survey>);
			OnCreated();
		}
		
		[Column(Storage="_SectionId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SectionId
		{
			get
			{
				return this._SectionId;
			}
			set
			{
				if ((this._SectionId != value))
				{
					this.OnSectionIdChanging(value);
					this.SendPropertyChanging();
					this._SectionId = value;
					this.SendPropertyChanged("SectionId");
					this.OnSectionIdChanged();
				}
			}
		}
		
		[Column(Storage="_SurveyId", DbType="Int NOT NULL")]
		public int SurveyId
		{
			get
			{
				return this._SurveyId;
			}
			set
			{
				if ((this._SurveyId != value))
				{
					if (this._Survey.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSurveyIdChanging(value);
					this.SendPropertyChanging();
					this._SurveyId = value;
					this.SendPropertyChanged("SurveyId");
					this.OnSurveyIdChanged();
				}
			}
		}
		
		[Column(Storage="_Text", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[Column(Storage="_ShowText", DbType="Bit NOT NULL")]
		public bool ShowText
		{
			get
			{
				return this._ShowText;
			}
			set
			{
				if ((this._ShowText != value))
				{
					this.OnShowTextChanging(value);
					this.SendPropertyChanging();
					this._ShowText = value;
					this.SendPropertyChanged("ShowText");
					this.OnShowTextChanged();
				}
			}
		}
		
		[Column(Storage="_RelativeOrder", DbType="Int NOT NULL")]
		public int RelativeOrder
		{
			get
			{
				return this._RelativeOrder;
			}
			set
			{
				if ((this._RelativeOrder != value))
				{
					this.OnRelativeOrderChanging(value);
					this.SendPropertyChanging();
					this._RelativeOrder = value;
					this.SendPropertyChanged("RelativeOrder");
					this.OnRelativeOrderChanged();
				}
			}
		}
		
		[Column(Storage="_RevisingUser", DbType="Int NOT NULL")]
		public int RevisingUser
		{
			get
			{
				return this._RevisingUser;
			}
			set
			{
				if ((this._RevisingUser != value))
				{
					this.OnRevisingUserChanging(value);
					this.SendPropertyChanging();
					this._RevisingUser = value;
					this.SendPropertyChanged("RevisingUser");
					this.OnRevisingUserChanged();
				}
			}
		}
		
		[Column(Storage="_RevisionDate", DbType="DateTime NOT NULL")]
		public System.DateTime RevisionDate
		{
			get
			{
				return this._RevisionDate;
			}
			set
			{
				if ((this._RevisionDate != value))
				{
					this.OnRevisionDateChanging(value);
					this.SendPropertyChanging();
					this._RevisionDate = value;
					this.SendPropertyChanged("RevisionDate");
					this.OnRevisionDateChanged();
				}
			}
		}
		
		[Column(Storage="_CreatedBy", DbType="Int NOT NULL")]
		public int CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[Column(Storage="_CreationDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreationDate
		{
			get
			{
				return this._CreationDate;
			}
			set
			{
				if ((this._CreationDate != value))
				{
					this.OnCreationDateChanging(value);
					this.SendPropertyChanging();
					this._CreationDate = value;
					this.SendPropertyChanged("CreationDate");
					this.OnCreationDateChanged();
				}
			}
		}
		
		[Association(Name="Section_Question", Storage="_Questions", ThisKey="SectionId", OtherKey="SectionId")]
		public EntitySet<Question> Questions
		{
			get
			{
				return this._Questions;
			}
			set
			{
				this._Questions.Assign(value);
			}
		}
		
		[Association(Name="EngageSurvey_Survey_Section", Storage="_Survey", ThisKey="SurveyId", OtherKey="SurveyId", IsForeignKey=true)]
		public Survey Survey
		{
			get
			{
				return this._Survey.Entity;
			}
			set
			{
				Survey previousValue = this._Survey.Entity;
				if (((previousValue != value) 
							|| (this._Survey.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Survey.Entity = null;
						previousValue.Sections.Remove(this);
					}
					this._Survey.Entity = value;
					if ((value != null))
					{
						value.Sections.Add(this);
						this._SurveyId = value.SurveyId;
					}
					else
					{
						this._SurveyId = default(int);
					}
					this.SendPropertyChanged("Survey");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Questions(Question entity)
		{
			this.SendPropertyChanging();
			entity.Section = this;
		}
		
		private void detach_Questions(Question entity)
		{
			this.SendPropertyChanging();
			entity.Section = null;
		}
	}
	
	[Table(Name="dbo.EngageSurvey_Answer")]
	public partial class Answer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AnswerId;
		
		private int _QuestionId;
		
		private string _Text;
		
		private bool _IsCorrect;
		
		private int _RelativeOrder;
		
		private int _RevisingUser;
		
		private System.DateTime _RevisionDate;
		
		private int _CreatedBy;
		
		private System.DateTime _CreationDate;
		
		private EntityRef<Question> _Question;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAnswerIdChanging(int value);
    partial void OnAnswerIdChanged();
    partial void OnQuestionIdChanging(int value);
    partial void OnQuestionIdChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    partial void OnIsCorrectChanging(bool value);
    partial void OnIsCorrectChanged();
    partial void OnRelativeOrderChanging(int value);
    partial void OnRelativeOrderChanged();
    partial void OnRevisingUserChanging(int value);
    partial void OnRevisingUserChanged();
    partial void OnRevisionDateChanging(System.DateTime value);
    partial void OnRevisionDateChanged();
    partial void OnCreatedByChanging(int value);
    partial void OnCreatedByChanged();
    partial void OnCreationDateChanging(System.DateTime value);
    partial void OnCreationDateChanged();
    #endregion
		
		public Answer()
		{
			this._Question = default(EntityRef<Question>);
			OnCreated();
		}
		
		[Column(Storage="_AnswerId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AnswerId
		{
			get
			{
				return this._AnswerId;
			}
			set
			{
				if ((this._AnswerId != value))
				{
					this.OnAnswerIdChanging(value);
					this.SendPropertyChanging();
					this._AnswerId = value;
					this.SendPropertyChanged("AnswerId");
					this.OnAnswerIdChanged();
				}
			}
		}
		
		[Column(Storage="_QuestionId", DbType="Int NOT NULL")]
		public int QuestionId
		{
			get
			{
				return this._QuestionId;
			}
			set
			{
				if ((this._QuestionId != value))
				{
					if (this._Question.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnQuestionIdChanging(value);
					this.SendPropertyChanging();
					this._QuestionId = value;
					this.SendPropertyChanged("QuestionId");
					this.OnQuestionIdChanged();
				}
			}
		}
		
		[Column(Storage="_Text", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[Column(Storage="_IsCorrect", DbType="Bit NOT NULL")]
		public bool IsCorrect
		{
			get
			{
				return this._IsCorrect;
			}
			set
			{
				if ((this._IsCorrect != value))
				{
					this.OnIsCorrectChanging(value);
					this.SendPropertyChanging();
					this._IsCorrect = value;
					this.SendPropertyChanged("IsCorrect");
					this.OnIsCorrectChanged();
				}
			}
		}
		
		[Column(Storage="_RelativeOrder", DbType="Int NOT NULL")]
		public int RelativeOrder
		{
			get
			{
				return this._RelativeOrder;
			}
			set
			{
				if ((this._RelativeOrder != value))
				{
					this.OnRelativeOrderChanging(value);
					this.SendPropertyChanging();
					this._RelativeOrder = value;
					this.SendPropertyChanged("RelativeOrder");
					this.OnRelativeOrderChanged();
				}
			}
		}
		
		[Column(Storage="_RevisingUser", DbType="Int NOT NULL")]
		public int RevisingUser
		{
			get
			{
				return this._RevisingUser;
			}
			set
			{
				if ((this._RevisingUser != value))
				{
					this.OnRevisingUserChanging(value);
					this.SendPropertyChanging();
					this._RevisingUser = value;
					this.SendPropertyChanged("RevisingUser");
					this.OnRevisingUserChanged();
				}
			}
		}
		
		[Column(Storage="_RevisionDate", DbType="DateTime NOT NULL")]
		public System.DateTime RevisionDate
		{
			get
			{
				return this._RevisionDate;
			}
			set
			{
				if ((this._RevisionDate != value))
				{
					this.OnRevisionDateChanging(value);
					this.SendPropertyChanging();
					this._RevisionDate = value;
					this.SendPropertyChanged("RevisionDate");
					this.OnRevisionDateChanged();
				}
			}
		}
		
		[Column(Storage="_CreatedBy", DbType="Int NOT NULL")]
		public int CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[Column(Storage="_CreationDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreationDate
		{
			get
			{
				return this._CreationDate;
			}
			set
			{
				if ((this._CreationDate != value))
				{
					this.OnCreationDateChanging(value);
					this.SendPropertyChanging();
					this._CreationDate = value;
					this.SendPropertyChanged("CreationDate");
					this.OnCreationDateChanged();
				}
			}
		}
		
		[Association(Name="Question_Answer", Storage="_Question", ThisKey="QuestionId", OtherKey="QuestionId", IsForeignKey=true)]
		public Question Question
		{
			get
			{
				return this._Question.Entity;
			}
			set
			{
				Question previousValue = this._Question.Entity;
				if (((previousValue != value) 
							|| (this._Question.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Question.Entity = null;
						previousValue.Answers.Remove(this);
					}
					this._Question.Entity = value;
					if ((value != null))
					{
						value.Answers.Add(this);
						this._QuestionId = value.QuestionId;
					}
					else
					{
						this._QuestionId = default(int);
					}
					this.SendPropertyChanged("Question");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.EngageSurvey_ResponseHeader")]
	public partial class ResponseHeader : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ResponseHeaderId;
		
		private System.Nullable<int> _UserId;
		
		private int _RevisingUser;
		
		private System.DateTime _RevisionDate;
		
		private int _CreatedBy;
		
		private System.DateTime _CreationDate;
		
		private EntitySet<Response> _Responses;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnResponseHeaderIdChanging(int value);
    partial void OnResponseHeaderIdChanged();
    partial void OnUserIdChanging(System.Nullable<int> value);
    partial void OnUserIdChanged();
    partial void OnRevisingUserChanging(int value);
    partial void OnRevisingUserChanged();
    partial void OnRevisionDateChanging(System.DateTime value);
    partial void OnRevisionDateChanged();
    partial void OnCreatedByChanging(int value);
    partial void OnCreatedByChanged();
    partial void OnCreationDateChanging(System.DateTime value);
    partial void OnCreationDateChanged();
    #endregion
		
		public ResponseHeader()
		{
			this._Responses = new EntitySet<Response>(new Action<Response>(this.attach_Responses), new Action<Response>(this.detach_Responses));
			OnCreated();
		}
		
		[Column(Storage="_ResponseHeaderId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ResponseHeaderId
		{
			get
			{
				return this._ResponseHeaderId;
			}
			set
			{
				if ((this._ResponseHeaderId != value))
				{
					this.OnResponseHeaderIdChanging(value);
					this.SendPropertyChanging();
					this._ResponseHeaderId = value;
					this.SendPropertyChanged("ResponseHeaderId");
					this.OnResponseHeaderIdChanged();
				}
			}
		}
		
		[Column(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[Column(Storage="_RevisingUser", DbType="Int NOT NULL")]
		public int RevisingUser
		{
			get
			{
				return this._RevisingUser;
			}
			set
			{
				if ((this._RevisingUser != value))
				{
					this.OnRevisingUserChanging(value);
					this.SendPropertyChanging();
					this._RevisingUser = value;
					this.SendPropertyChanged("RevisingUser");
					this.OnRevisingUserChanged();
				}
			}
		}
		
		[Column(Storage="_RevisionDate", DbType="DateTime NOT NULL")]
		public System.DateTime RevisionDate
		{
			get
			{
				return this._RevisionDate;
			}
			set
			{
				if ((this._RevisionDate != value))
				{
					this.OnRevisionDateChanging(value);
					this.SendPropertyChanging();
					this._RevisionDate = value;
					this.SendPropertyChanged("RevisionDate");
					this.OnRevisionDateChanged();
				}
			}
		}
		
		[Column(Storage="_CreatedBy", DbType="Int NOT NULL")]
		public int CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[Column(Storage="_CreationDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreationDate
		{
			get
			{
				return this._CreationDate;
			}
			set
			{
				if ((this._CreationDate != value))
				{
					this.OnCreationDateChanging(value);
					this.SendPropertyChanging();
					this._CreationDate = value;
					this.SendPropertyChanged("CreationDate");
					this.OnCreationDateChanged();
				}
			}
		}
		
		[Association(Name="ResponseHeader_EngageSurvey_Response", Storage="_Responses", ThisKey="ResponseHeaderId", OtherKey="ResponseHeaderId")]
		public EntitySet<Response> Responses
		{
			get
			{
				return this._Responses;
			}
			set
			{
				this._Responses.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Responses(Response entity)
		{
			this.SendPropertyChanging();
			entity.ResponseHeader = this;
		}
		
		private void detach_Responses(Response entity)
		{
			this.SendPropertyChanging();
			entity.ResponseHeader = null;
		}
	}
	
	[Table(Name="dbo.EngageSurvey_Survey")]
	public partial class Survey : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SurveyId;
		
		private string _Text;
		
		private string _FinalMessageOption;
		
		private string _FinalMessage;
		
		private string _FinalUrl;
		
		private bool _ShowText;
		
		private string _QuestionFormatOption;
		
		private string _SectionFormatOption;
		
		private string _TitleOption;
		
		private string _LogoURL;
		
		private int _RevisingUser;
		
		private System.DateTime _RevisionDate;
		
		private int _CreatedBy;
		
		private System.DateTime _CreationDate;
		
		private EntitySet<Section> _Sections;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSurveyIdChanging(int value);
    partial void OnSurveyIdChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    partial void OnFinalMessageOptionChanging(string value);
    partial void OnFinalMessageOptionChanged();
    partial void OnFinalMessageChanging(string value);
    partial void OnFinalMessageChanged();
    partial void OnFinalUrlChanging(string value);
    partial void OnFinalUrlChanged();
    partial void OnShowTextChanging(bool value);
    partial void OnShowTextChanged();
    partial void OnQuestionFormatOptionChanging(string value);
    partial void OnQuestionFormatOptionChanged();
    partial void OnSectionFormatOptionChanging(string value);
    partial void OnSectionFormatOptionChanged();
    partial void OnTitleOptionChanging(string value);
    partial void OnTitleOptionChanged();
    partial void OnLogoURLChanging(string value);
    partial void OnLogoURLChanged();
    partial void OnRevisingUserChanging(int value);
    partial void OnRevisingUserChanged();
    partial void OnRevisionDateChanging(System.DateTime value);
    partial void OnRevisionDateChanged();
    partial void OnCreatedByChanging(int value);
    partial void OnCreatedByChanged();
    partial void OnCreationDateChanging(System.DateTime value);
    partial void OnCreationDateChanged();
    #endregion
		
		public Survey()
		{
			this._Sections = new EntitySet<Section>(new Action<Section>(this.attach_Sections), new Action<Section>(this.detach_Sections));
			OnCreated();
		}
		
		[Column(Storage="_SurveyId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SurveyId
		{
			get
			{
				return this._SurveyId;
			}
			set
			{
				if ((this._SurveyId != value))
				{
					this.OnSurveyIdChanging(value);
					this.SendPropertyChanging();
					this._SurveyId = value;
					this.SendPropertyChanged("SurveyId");
					this.OnSurveyIdChanged();
				}
			}
		}
		
		[Column(Storage="_Text", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[Column(Storage="_FinalMessageOption", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string FinalMessageOption
		{
			get
			{
				return this._FinalMessageOption;
			}
			set
			{
				if ((this._FinalMessageOption != value))
				{
					this.OnFinalMessageOptionChanging(value);
					this.SendPropertyChanging();
					this._FinalMessageOption = value;
					this.SendPropertyChanged("FinalMessageOption");
					this.OnFinalMessageOptionChanged();
				}
			}
		}
		
		[Column(Storage="_FinalMessage", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string FinalMessage
		{
			get
			{
				return this._FinalMessage;
			}
			set
			{
				if ((this._FinalMessage != value))
				{
					this.OnFinalMessageChanging(value);
					this.SendPropertyChanging();
					this._FinalMessage = value;
					this.SendPropertyChanged("FinalMessage");
					this.OnFinalMessageChanged();
				}
			}
		}
		
		[Column(Storage="_FinalUrl", DbType="NVarChar(256)")]
		public string FinalUrl
		{
			get
			{
				return this._FinalUrl;
			}
			set
			{
				if ((this._FinalUrl != value))
				{
					this.OnFinalUrlChanging(value);
					this.SendPropertyChanging();
					this._FinalUrl = value;
					this.SendPropertyChanged("FinalUrl");
					this.OnFinalUrlChanged();
				}
			}
		}
		
		[Column(Storage="_ShowText", DbType="Bit NOT NULL")]
		public bool ShowText
		{
			get
			{
				return this._ShowText;
			}
			set
			{
				if ((this._ShowText != value))
				{
					this.OnShowTextChanging(value);
					this.SendPropertyChanging();
					this._ShowText = value;
					this.SendPropertyChanged("ShowText");
					this.OnShowTextChanged();
				}
			}
		}
		
		[Column(Storage="_QuestionFormatOption", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string QuestionFormatOption
		{
			get
			{
				return this._QuestionFormatOption;
			}
			set
			{
				if ((this._QuestionFormatOption != value))
				{
					this.OnQuestionFormatOptionChanging(value);
					this.SendPropertyChanging();
					this._QuestionFormatOption = value;
					this.SendPropertyChanged("QuestionFormatOption");
					this.OnQuestionFormatOptionChanged();
				}
			}
		}
		
		[Column(Storage="_SectionFormatOption", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string SectionFormatOption
		{
			get
			{
				return this._SectionFormatOption;
			}
			set
			{
				if ((this._SectionFormatOption != value))
				{
					this.OnSectionFormatOptionChanging(value);
					this.SendPropertyChanging();
					this._SectionFormatOption = value;
					this.SendPropertyChanged("SectionFormatOption");
					this.OnSectionFormatOptionChanged();
				}
			}
		}
		
		[Column(Storage="_TitleOption", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string TitleOption
		{
			get
			{
				return this._TitleOption;
			}
			set
			{
				if ((this._TitleOption != value))
				{
					this.OnTitleOptionChanging(value);
					this.SendPropertyChanging();
					this._TitleOption = value;
					this.SendPropertyChanged("TitleOption");
					this.OnTitleOptionChanged();
				}
			}
		}
		
		[Column(Storage="_LogoURL", DbType="NVarChar(256)")]
		public string LogoURL
		{
			get
			{
				return this._LogoURL;
			}
			set
			{
				if ((this._LogoURL != value))
				{
					this.OnLogoURLChanging(value);
					this.SendPropertyChanging();
					this._LogoURL = value;
					this.SendPropertyChanged("LogoURL");
					this.OnLogoURLChanged();
				}
			}
		}
		
		[Column(Storage="_RevisingUser", DbType="Int NOT NULL")]
		public int RevisingUser
		{
			get
			{
				return this._RevisingUser;
			}
			set
			{
				if ((this._RevisingUser != value))
				{
					this.OnRevisingUserChanging(value);
					this.SendPropertyChanging();
					this._RevisingUser = value;
					this.SendPropertyChanged("RevisingUser");
					this.OnRevisingUserChanged();
				}
			}
		}
		
		[Column(Storage="_RevisionDate", DbType="DateTime NOT NULL")]
		public System.DateTime RevisionDate
		{
			get
			{
				return this._RevisionDate;
			}
			set
			{
				if ((this._RevisionDate != value))
				{
					this.OnRevisionDateChanging(value);
					this.SendPropertyChanging();
					this._RevisionDate = value;
					this.SendPropertyChanged("RevisionDate");
					this.OnRevisionDateChanged();
				}
			}
		}
		
		[Column(Storage="_CreatedBy", DbType="Int NOT NULL")]
		public int CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[Column(Storage="_CreationDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreationDate
		{
			get
			{
				return this._CreationDate;
			}
			set
			{
				if ((this._CreationDate != value))
				{
					this.OnCreationDateChanging(value);
					this.SendPropertyChanging();
					this._CreationDate = value;
					this.SendPropertyChanged("CreationDate");
					this.OnCreationDateChanged();
				}
			}
		}
		
		[Association(Name="EngageSurvey_Survey_Section", Storage="_Sections", ThisKey="SurveyId", OtherKey="SurveyId")]
		internal EntitySet<Section> Sections
		{
			get
			{
				return this._Sections;
			}
			set
			{
				this._Sections.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sections(Section entity)
		{
			this.SendPropertyChanging();
			entity.Survey = this;
		}
		
		private void detach_Sections(Section entity)
		{
			this.SendPropertyChanging();
			entity.Survey = null;
		}
	}
	
	[Table(Name="dbo.EngageSurvey_Response")]
	public partial class Response : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ResponseId;
		
		private int _SurveyId;
		
		private int _ResponseHeaderId;
		
		private string _SurveyText;
		
		private bool _ShowSurveyText;
		
		private string _TitleOption;
		
		private int _SectionId;
		
		private string _SectionText;
		
		private int _SectionRelativeOrder;
		
		private bool _ShowSectionText;
		
		private int _QuestionId;
		
		private string _QuestionText;
		
		private string _Comments;
		
		private int _QuestionRelativeOrder;
		
		private string _QuestionFormatOption;
		
		private string _ControlType;
		
		private System.Nullable<int> _AnswerId;
		
		private string _SectionFormatOption;
		
		private string _AnswerText;
		
		private System.Nullable<int> _AnswerRelativeOrder;
		
		private System.Nullable<bool> _AnswerIsCorrect;
		
		private string _UserResponse;
		
		private int _RevisingUser;
		
		private System.DateTime _RevisionDate;
		
		private int _CreatedBy;
		
		private System.DateTime _CreationDate;
		
		private EntityRef<ResponseHeader> _ResponseHeader;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnResponseIdChanging(int value);
    partial void OnResponseIdChanged();
    partial void OnSurveyIdChanging(int value);
    partial void OnSurveyIdChanged();
    partial void OnResponseHeaderIdChanging(int value);
    partial void OnResponseHeaderIdChanged();
    partial void OnSurveyTextChanging(string value);
    partial void OnSurveyTextChanged();
    partial void OnShowSurveyTextChanging(bool value);
    partial void OnShowSurveyTextChanged();
    partial void OnTitleOptionChanging(string value);
    partial void OnTitleOptionChanged();
    partial void OnSectionIdChanging(int value);
    partial void OnSectionIdChanged();
    partial void OnSectionTextChanging(string value);
    partial void OnSectionTextChanged();
    partial void OnSectionRelativeOrderChanging(int value);
    partial void OnSectionRelativeOrderChanged();
    partial void OnShowSectionTextChanging(bool value);
    partial void OnShowSectionTextChanged();
    partial void OnQuestionIdChanging(int value);
    partial void OnQuestionIdChanged();
    partial void OnQuestionTextChanging(string value);
    partial void OnQuestionTextChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    partial void OnQuestionRelativeOrderChanging(int value);
    partial void OnQuestionRelativeOrderChanged();
    partial void OnQuestionFormatOptionChanging(string value);
    partial void OnQuestionFormatOptionChanged();
    partial void OnControlTypeChanging(string value);
    partial void OnControlTypeChanged();
    partial void OnAnswerIdChanging(System.Nullable<int> value);
    partial void OnAnswerIdChanged();
    partial void OnSectionFormatOptionChanging(string value);
    partial void OnSectionFormatOptionChanged();
    partial void OnAnswerTextChanging(string value);
    partial void OnAnswerTextChanged();
    partial void OnAnswerRelativeOrderChanging(System.Nullable<int> value);
    partial void OnAnswerRelativeOrderChanged();
    partial void OnAnswerIsCorrectChanging(System.Nullable<bool> value);
    partial void OnAnswerIsCorrectChanged();
    partial void OnUserResponseChanging(string value);
    partial void OnUserResponseChanged();
    partial void OnRevisingUserChanging(int value);
    partial void OnRevisingUserChanged();
    partial void OnRevisionDateChanging(System.DateTime value);
    partial void OnRevisionDateChanged();
    partial void OnCreatedByChanging(int value);
    partial void OnCreatedByChanged();
    partial void OnCreationDateChanging(System.DateTime value);
    partial void OnCreationDateChanged();
    #endregion
		
		public Response()
		{
			this._ResponseHeader = default(EntityRef<ResponseHeader>);
			OnCreated();
		}
		
		[Column(Storage="_ResponseId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ResponseId
		{
			get
			{
				return this._ResponseId;
			}
			set
			{
				if ((this._ResponseId != value))
				{
					this.OnResponseIdChanging(value);
					this.SendPropertyChanging();
					this._ResponseId = value;
					this.SendPropertyChanged("ResponseId");
					this.OnResponseIdChanged();
				}
			}
		}
		
		[Column(Storage="_SurveyId", DbType="Int NOT NULL")]
		public int SurveyId
		{
			get
			{
				return this._SurveyId;
			}
			set
			{
				if ((this._SurveyId != value))
				{
					this.OnSurveyIdChanging(value);
					this.SendPropertyChanging();
					this._SurveyId = value;
					this.SendPropertyChanged("SurveyId");
					this.OnSurveyIdChanged();
				}
			}
		}
		
		[Column(Storage="_ResponseHeaderId", DbType="Int NOT NULL")]
		public int ResponseHeaderId
		{
			get
			{
				return this._ResponseHeaderId;
			}
			set
			{
				if ((this._ResponseHeaderId != value))
				{
					if (this._ResponseHeader.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnResponseHeaderIdChanging(value);
					this.SendPropertyChanging();
					this._ResponseHeaderId = value;
					this.SendPropertyChanged("ResponseHeaderId");
					this.OnResponseHeaderIdChanged();
				}
			}
		}
		
		[Column(Storage="_SurveyText", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string SurveyText
		{
			get
			{
				return this._SurveyText;
			}
			set
			{
				if ((this._SurveyText != value))
				{
					this.OnSurveyTextChanging(value);
					this.SendPropertyChanging();
					this._SurveyText = value;
					this.SendPropertyChanged("SurveyText");
					this.OnSurveyTextChanged();
				}
			}
		}
		
		[Column(Storage="_ShowSurveyText", DbType="Bit NOT NULL")]
		public bool ShowSurveyText
		{
			get
			{
				return this._ShowSurveyText;
			}
			set
			{
				if ((this._ShowSurveyText != value))
				{
					this.OnShowSurveyTextChanging(value);
					this.SendPropertyChanging();
					this._ShowSurveyText = value;
					this.SendPropertyChanged("ShowSurveyText");
					this.OnShowSurveyTextChanged();
				}
			}
		}
		
		[Column(Storage="_TitleOption", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string TitleOption
		{
			get
			{
				return this._TitleOption;
			}
			set
			{
				if ((this._TitleOption != value))
				{
					this.OnTitleOptionChanging(value);
					this.SendPropertyChanging();
					this._TitleOption = value;
					this.SendPropertyChanged("TitleOption");
					this.OnTitleOptionChanged();
				}
			}
		}
		
		[Column(Storage="_SectionId", DbType="Int NOT NULL")]
		public int SectionId
		{
			get
			{
				return this._SectionId;
			}
			set
			{
				if ((this._SectionId != value))
				{
					this.OnSectionIdChanging(value);
					this.SendPropertyChanging();
					this._SectionId = value;
					this.SendPropertyChanged("SectionId");
					this.OnSectionIdChanged();
				}
			}
		}
		
		[Column(Storage="_SectionText", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string SectionText
		{
			get
			{
				return this._SectionText;
			}
			set
			{
				if ((this._SectionText != value))
				{
					this.OnSectionTextChanging(value);
					this.SendPropertyChanging();
					this._SectionText = value;
					this.SendPropertyChanged("SectionText");
					this.OnSectionTextChanged();
				}
			}
		}
		
		[Column(Storage="_SectionRelativeOrder", DbType="Int NOT NULL")]
		public int SectionRelativeOrder
		{
			get
			{
				return this._SectionRelativeOrder;
			}
			set
			{
				if ((this._SectionRelativeOrder != value))
				{
					this.OnSectionRelativeOrderChanging(value);
					this.SendPropertyChanging();
					this._SectionRelativeOrder = value;
					this.SendPropertyChanged("SectionRelativeOrder");
					this.OnSectionRelativeOrderChanged();
				}
			}
		}
		
		[Column(Storage="_ShowSectionText", DbType="Bit NOT NULL")]
		public bool ShowSectionText
		{
			get
			{
				return this._ShowSectionText;
			}
			set
			{
				if ((this._ShowSectionText != value))
				{
					this.OnShowSectionTextChanging(value);
					this.SendPropertyChanging();
					this._ShowSectionText = value;
					this.SendPropertyChanged("ShowSectionText");
					this.OnShowSectionTextChanged();
				}
			}
		}
		
		[Column(Storage="_QuestionId", DbType="Int NOT NULL")]
		public int QuestionId
		{
			get
			{
				return this._QuestionId;
			}
			set
			{
				if ((this._QuestionId != value))
				{
					this.OnQuestionIdChanging(value);
					this.SendPropertyChanging();
					this._QuestionId = value;
					this.SendPropertyChanged("QuestionId");
					this.OnQuestionIdChanged();
				}
			}
		}
		
		[Column(Storage="_QuestionText", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string QuestionText
		{
			get
			{
				return this._QuestionText;
			}
			set
			{
				if ((this._QuestionText != value))
				{
					this.OnQuestionTextChanging(value);
					this.SendPropertyChanging();
					this._QuestionText = value;
					this.SendPropertyChanged("QuestionText");
					this.OnQuestionTextChanged();
				}
			}
		}
		
		[Column(Storage="_Comments", DbType="NVarChar(4000)")]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this.OnCommentsChanging(value);
					this.SendPropertyChanging();
					this._Comments = value;
					this.SendPropertyChanged("Comments");
					this.OnCommentsChanged();
				}
			}
		}
		
		[Column(Storage="_QuestionRelativeOrder", DbType="Int NOT NULL")]
		public int QuestionRelativeOrder
		{
			get
			{
				return this._QuestionRelativeOrder;
			}
			set
			{
				if ((this._QuestionRelativeOrder != value))
				{
					this.OnQuestionRelativeOrderChanging(value);
					this.SendPropertyChanging();
					this._QuestionRelativeOrder = value;
					this.SendPropertyChanged("QuestionRelativeOrder");
					this.OnQuestionRelativeOrderChanged();
				}
			}
		}
		
		[Column(Storage="_QuestionFormatOption", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string QuestionFormatOption
		{
			get
			{
				return this._QuestionFormatOption;
			}
			set
			{
				if ((this._QuestionFormatOption != value))
				{
					this.OnQuestionFormatOptionChanging(value);
					this.SendPropertyChanging();
					this._QuestionFormatOption = value;
					this.SendPropertyChanged("QuestionFormatOption");
					this.OnQuestionFormatOptionChanged();
				}
			}
		}
		
		[Column(Storage="_ControlType", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string ControlType
		{
			get
			{
				return this._ControlType;
			}
			set
			{
				if ((this._ControlType != value))
				{
					this.OnControlTypeChanging(value);
					this.SendPropertyChanging();
					this._ControlType = value;
					this.SendPropertyChanged("ControlType");
					this.OnControlTypeChanged();
				}
			}
		}
		
		[Column(Storage="_AnswerId", DbType="Int")]
		public System.Nullable<int> AnswerId
		{
			get
			{
				return this._AnswerId;
			}
			set
			{
				if ((this._AnswerId != value))
				{
					this.OnAnswerIdChanging(value);
					this.SendPropertyChanging();
					this._AnswerId = value;
					this.SendPropertyChanged("AnswerId");
					this.OnAnswerIdChanged();
				}
			}
		}
		
		[Column(Storage="_SectionFormatOption", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string SectionFormatOption
		{
			get
			{
				return this._SectionFormatOption;
			}
			set
			{
				if ((this._SectionFormatOption != value))
				{
					this.OnSectionFormatOptionChanging(value);
					this.SendPropertyChanging();
					this._SectionFormatOption = value;
					this.SendPropertyChanged("SectionFormatOption");
					this.OnSectionFormatOptionChanged();
				}
			}
		}
		
		[Column(Storage="_AnswerText", DbType="NVarChar(256)")]
		public string AnswerText
		{
			get
			{
				return this._AnswerText;
			}
			set
			{
				if ((this._AnswerText != value))
				{
					this.OnAnswerTextChanging(value);
					this.SendPropertyChanging();
					this._AnswerText = value;
					this.SendPropertyChanged("AnswerText");
					this.OnAnswerTextChanged();
				}
			}
		}
		
		[Column(Storage="_AnswerRelativeOrder", DbType="Int")]
		public System.Nullable<int> AnswerRelativeOrder
		{
			get
			{
				return this._AnswerRelativeOrder;
			}
			set
			{
				if ((this._AnswerRelativeOrder != value))
				{
					this.OnAnswerRelativeOrderChanging(value);
					this.SendPropertyChanging();
					this._AnswerRelativeOrder = value;
					this.SendPropertyChanged("AnswerRelativeOrder");
					this.OnAnswerRelativeOrderChanged();
				}
			}
		}
		
		[Column(Storage="_AnswerIsCorrect", DbType="Bit")]
		public System.Nullable<bool> AnswerIsCorrect
		{
			get
			{
				return this._AnswerIsCorrect;
			}
			set
			{
				if ((this._AnswerIsCorrect != value))
				{
					this.OnAnswerIsCorrectChanging(value);
					this.SendPropertyChanging();
					this._AnswerIsCorrect = value;
					this.SendPropertyChanged("AnswerIsCorrect");
					this.OnAnswerIsCorrectChanged();
				}
			}
		}
		
		[Column(Storage="_UserResponse", DbType="NVarChar(4000)")]
		public string UserResponse
		{
			get
			{
				return this._UserResponse;
			}
			set
			{
				if ((this._UserResponse != value))
				{
					this.OnUserResponseChanging(value);
					this.SendPropertyChanging();
					this._UserResponse = value;
					this.SendPropertyChanged("UserResponse");
					this.OnUserResponseChanged();
				}
			}
		}
		
		[Column(Storage="_RevisingUser", DbType="Int NOT NULL")]
		public int RevisingUser
		{
			get
			{
				return this._RevisingUser;
			}
			set
			{
				if ((this._RevisingUser != value))
				{
					this.OnRevisingUserChanging(value);
					this.SendPropertyChanging();
					this._RevisingUser = value;
					this.SendPropertyChanged("RevisingUser");
					this.OnRevisingUserChanged();
				}
			}
		}
		
		[Column(Storage="_RevisionDate", DbType="DateTime NOT NULL")]
		public System.DateTime RevisionDate
		{
			get
			{
				return this._RevisionDate;
			}
			set
			{
				if ((this._RevisionDate != value))
				{
					this.OnRevisionDateChanging(value);
					this.SendPropertyChanging();
					this._RevisionDate = value;
					this.SendPropertyChanged("RevisionDate");
					this.OnRevisionDateChanged();
				}
			}
		}
		
		[Column(Storage="_CreatedBy", DbType="Int NOT NULL")]
		public int CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[Column(Storage="_CreationDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreationDate
		{
			get
			{
				return this._CreationDate;
			}
			set
			{
				if ((this._CreationDate != value))
				{
					this.OnCreationDateChanging(value);
					this.SendPropertyChanging();
					this._CreationDate = value;
					this.SendPropertyChanged("CreationDate");
					this.OnCreationDateChanged();
				}
			}
		}
		
		[Association(Name="ResponseHeader_EngageSurvey_Response", Storage="_ResponseHeader", ThisKey="ResponseHeaderId", OtherKey="ResponseHeaderId", IsForeignKey=true)]
		public ResponseHeader ResponseHeader
		{
			get
			{
				return this._ResponseHeader.Entity;
			}
			set
			{
				ResponseHeader previousValue = this._ResponseHeader.Entity;
				if (((previousValue != value) 
							|| (this._ResponseHeader.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ResponseHeader.Entity = null;
						previousValue.Responses.Remove(this);
					}
					this._ResponseHeader.Entity = value;
					if ((value != null))
					{
						value.Responses.Add(this);
						this._ResponseHeaderId = value.ResponseHeaderId;
					}
					else
					{
						this._ResponseHeaderId = default(int);
					}
					this.SendPropertyChanged("ResponseHeader");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
